# 실습1

In [3]:
def my_len(x):
    length = 0

    for i in x:
        length += 1
    
    return length

a = [5,5,6,7,8,3]
b = 'Life is short.'
print(len(a), len(b)) # 내장 함수 len()
print(my_len(a), my_len(b))

6 14
6 14


# 실습2

In [4]:
def mult(a, b):
    result = 1

    for i in range(a,b+1):
        result = result*i
    
    return result 

print(mult(1,3))
print(mult(2,5))

6
120


# 실습3

In [5]:
def sum_pos_neg(l):

    a=0
    b=0

    for i in l:
        if i > 0:
            a += i
        else:
            b += i

    return (a,b)

possum, negsum = sum_pos_neg([3,4,-6,-3])
print(possum,negsum) # 7 -9
mylist = [0,0,0,0,0,0,0,0,0,1,-1]
possum2, negsum2 = sum_pos_neg(mylist)
print(possum2,negsum2) # 1 -1

7 -9
1 -1


# 실습4

In [1]:
def vector_sum(vector, *vectors): #나머지 변수는 * 별을 붙여주기!!
    result = [vector[0], vector[1]]  #Shallow copy 방지를 위해

    for v in vectors:
        result[0] += v[0]
        result[1] += v[1]

    return result

    
v1 = [0,1]
v2 = [0.5, 0.5]
v3 = [1,0]
v4 = [6,4]
v5 = [3.13, 2.72]
m1 = vector_sum(v1, v2, v3)
m2 = vector_sum(v1, v2, v3, v4)
m3 = vector_sum(v3, v5)
print(m1,m2,m3)

[1.5, 1.5] [7.5, 5.5] [4.13, 2.72]


# 실습5

In [2]:
def merge_list(l1=[0], l2=[0]):

    return sorted(l1+l2)

l = [3, 5, 9, 1, 2]
ml1 = merge_list(l,[2,1])
ml2 = merge_list([6,9,4])
ml3 = merge_list()
print(ml1) # [1, 1, 2, 2, 3, 5, 9]
print(ml2) # [0, 4, 6, 9]
print(ml3) # [0, 0]


[1, 1, 2, 2, 3, 5, 9]
[0, 4, 6, 9]
[0, 0]


# 실습6

In [6]:
import random

menu = ["된장찌개", "부대찌개", "김치찌개", "삼계탕", "파스타", "돈까스", "쌀국수"]
res = random.choice(menu)

print("오늘 점심은",res+"입니다.")

오늘 점심은 쌀국수입니다.


# 실습7

In [7]:
import random

print("** 로또 번호 자동 기입을 시작합니다 **")
 
for i in range(1,6):
    print(str(i)+"번째 자동 기입 ==> ", end= '')

    res=random.sample(range(1,45),6)
    res.sort()

    print(*res)

    
#print( *l) 하면 list에서 콤마 없이 공백으로 출력가능

** 로또 번호 자동 기입을 시작합니다 **
1번째 자동 기입 ==> 9 11 17 22 29 43
2번째 자동 기입 ==> 2 11 27 33 36 42
3번째 자동 기입 ==> 7 10 19 22 34 43
4번째 자동 기입 ==> 2 6 36 37 39 43
5번째 자동 기입 ==> 9 10 19 21 24 30


# 실습8

In [8]:
def get_min_max(l):

    min_val = min(l)
    max_val = max(l)

    l.remove(min_val)
    l.remove(max_val)

    return(min_val, max_val)

l = [3, 5, 9, 1, 2]
min_val, max_val = get_min_max(l)
print(min_val)
print(max_val)
print(l)

1
9
[3, 5, 2]


# 실습9

In [9]:
def comb_dict(d1, d2):
    d = d1  #shallow copy 발생 그래서 내장모듈 copy를 사용하여 deep copy해야함

    for k, v in d2.items():
        if k in d:
            d[k] += v
        else:
            d[k] = v
    return d


d1 = {'a': 1, 'b': 3, 'd': 7, 'e': 8}
d2 = {'a': 2, 'c': 4, 'e': 1}
d3 = comb_dict(d1, d2)
print(d3)
print(d1)  #Shallow copy때문에 덮어쓰기가 됨

{'a': 3, 'b': 3, 'd': 7, 'e': 9, 'c': 4}
{'a': 3, 'b': 3, 'd': 7, 'e': 9, 'c': 4}


In [10]:
import copy

def comb_dict(d1, d2):
    d = copy.deepcopy(d1)  #shallow copy 발생 그래서 내장모듈 copy를 사용하여 deep copy해야함

    for k, v in d2.items():
        if k in d:
            d[k] += v
        else:
            d[k] = v
    return d


d1 = {'a': 1, 'b': 3, 'd': 7, 'e': 8}
d2 = {'a': 2, 'c': 4, 'e': 1}
d3 = comb_dict(d1, d2)
print(d3)
print(d1)  #Shallow copy때문에 덮어쓰기 안됨

{'a': 3, 'b': 3, 'd': 7, 'e': 9, 'c': 4}
{'a': 1, 'b': 3, 'd': 7, 'e': 8}


# 실습10

In [11]:
def diff(*l):  #가변매개변수 기능 이용
    return (max(l)-min(l))

print(diff(1,2,3,4,5))
print(diff(-100, 200))

4
300


# 실습1

In [2]:
# 1) 파일명 입력 받기
filename = input("Enter a file name: ")

# 2) 파일 열기
f = open(filename,"r")

# 3) 파일 읽기
for line in f:
    print(line.upper(), end='')

f.close()

Enter a file name:  test.txt


FIRST LINE
SECOND LINE
THIRD LINE

# 실습2

In [4]:
# 1) score.txt(읽기모드), report.txt(쓰기모드) 열기
f_score = open("score.txt","r")
f_report = open("report.txt","w")

# 2) score.txt 파일 읽기
for line in f_score:

    # 3) 평균 계산
    sid, mid, fin = line.split() #문자열
    avg = (int(mid+fin))/2
    
    # 4) 힉잠 계산
    grade = 'A'

    if avg >= 90:
        grade = 'A'
    elif avg >= 80:
        grade = 'B'
    elif avg >= 70:
        grade = 'C'  
    elif avg >= 60:
        grade = 'D' 
    else:
        grade = 'F'

        
    # 5) report.txt.에 적을 문자열 만들기
    data = sid + "  " + str(avg) + "(" + grade + ") \n"
    #print(data)

    # 6) report.txt.에 쓰기
    f_report.write(data)


f_score.close()
f_report.close()

# 클래스 실습

In [1]:
class Person:
    def __init__(self,n,a,h,w):
        # 성명, 나이, 키, 몸무게 초기화
        self.name = n
        self.age = a
        self.height = h
        self.weight = w

    def add_age(self):
        # self의 나이를 1증가
        self.age += 1
    
    def change_height(self, h):
        # self의 키를 h로 세팅
        self.height = h
        
    def change_weight(self, w):
        # self의 키를 h로 세팅
        self.weight = w
        
    def get_info(self):
        print("이름: ", self.name)
        print("나이: ", self.age)
        print("키: ", self.height)
        print("몸무게: ", self.weight)

a = Person("홍길동",10,100,20) 
a.get_info()

print()

a.add_age()
a.get_info()

print()

a.change_weight(40)
a.get_info()


이름:  홍길동
나이:  10
키:  100
몸무게:  20

이름:  홍길동
나이:  11
키:  100
몸무게:  20

이름:  홍길동
나이:  11
키:  100
몸무게:  40


# Numpy

# 실습 문제1

In [4]:
import numpy as np

a = np.ones((5,5))
a[1:4,1:4]=0
print(a)
print()

a = np.zeros((5,5))
a[1:4,1:4]=1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
a = np.zeros((3,3))
b = np.pad(a, pad_width=1, mode='constant', constant_values=1)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 실습 문제2

In [11]:
a = np.zeros((8,8))

a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 실습 문제3

In [12]:
a = np.array([180, 72, 172, 66, 162, 60, 167, 53, 176, 80, 155, 60, 177, 77, 130, 40])
a.resize((2,4,2))
print(a)
print()

print(a[1,2,1])

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]

77


# 실습 문제4

# 실습 문제5